session_name: quant-arena
start_directory: ./

environment:
  QUANT_ARENA_URL_PREFIX: /quant-arena

windows:
  - window_name: main
    focus: true
    panes:
      - blank

  - window_name: config
    start_directory: ~/.quant-arena
    panes:
      - blank

  - window_name: deploy
    panes:
      - environment:
          QUANT_ARENA_URL_PREFIX: /quant-arena
        shell_command:
          - source .venv/bin/activate
          - uvicorn quant_arena.server:create_app --factory --host 127.0.0.1 --port 18792
